import {
  // ===== Dashboard & Navigation =====
  LayoutDashboard,
  FilePlus,
  ClipboardList,
  Users,
  BookOpen,
  BarChart3,
  Settings,
  LogOut,
  Bell,
  HelpCircle,
  Menu,
  Search,
  Plus,
  Pencil,
  Eye,
  Trash2,
  ChevronLeft,
  ChevronRight,
  X,
  Hexagon,
  FileText,
  CheckCircle,
  Edit,
  TrendingUp,
  Tag,
  Sparkles,
  Link2,
  Zap,
  Gem,
  Rocket,
  Globe,
  Calendar,
  Clock,
  User,
  ArrowLeft,
  ArrowRight,
  Send,
  Save,
  Image as ImageIcon,
  Cpu,
  PiggyBank,
  BadgeCheck,
  Database,
  ShieldCheck,
  Crown,
  RefreshCw,
  Printer,
  PieChart,
  Radar,
  Hash,
  Download,
  Link,
  ListOrdered,
  Underline,
  Italic,
  Bold,
  MapPin,
  Mail,
  Share2,
  RotateCcw,
  Wallet,
  UserCog,
  Info,
  AlertCircle,
  Check,
  Loader,
  Move,
  // Form Builder
  GripVertical,
  ArrowUp,
  ArrowDown,
  Copy,
  List,
  CheckSquare,
  ToggleLeft,
  Table,
  Type,
  AlignLeft,
  Grid,
  Grid3x3,
  Star,
  Sliders,
  Upload,
  Heading,
  Layout,
  LayoutDashboard as LayoutIcon,
  CircleDot,
  ChevronDown,
  ListChecks,
  Phone,
  Calendar as CalendarIcon,
  Mail as MailIcon,
  Hash as HashIcon,
} from "lucide-react"

export const Icons = {
  // ===== Dashboard & Navigation =====
  dashboard: LayoutDashboard,
  filePlus: FilePlus,
  clipboardList: ClipboardList,
  users: Users,
  bookOpen: BookOpen,
  barChart: BarChart3,
  settings: Settings,
  logout: LogOut,
  bell: Bell,
  helpCircle: HelpCircle,
  menu: Menu,
  search: Search,
  plus: Plus,
  pencil: Pencil,
  eye: Eye,
  trash: Trash2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  x: X,
  hexagon: Hexagon,
  fileText: FileText,
  checkCircle: CheckCircle,
  edit: Edit,
  trendingUp: TrendingUp,
  tag: Tag,
  sparkles: Sparkles,
  link2: Link2,
  zap: Zap,
  gem: Gem,
  rocket: Rocket,
  globe: Globe,
  calendar: Calendar,
  clock: Clock,
  user: User,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  send: Send,
  save: Save,
  image: ImageIcon,
  cpu: Cpu,
  piggyBank: PiggyBank,
  badgeCheck: BadgeCheck,
  database: Database,
  shieldCheck: ShieldCheck,
  crown: Crown,
  refreshCw: RefreshCw,
  printer: Printer,
  pieChart: PieChart,
  radar: Radar,
  hash: Hash,
  download: Download,
  link: Link,
  listOrdered: ListOrdered,
  underline: Underline,
  italic: Italic,
  bold: Bold,
  mapPin: MapPin,
  mail: Mail,
  share2: Share2,
  rotateCcw: RotateCcw,
  wallet: Wallet,
  userCog: UserCog,
  info: Info,
  alertCircle: AlertCircle,
  check: Check,
  loader: Loader,
  move: Move,

  // ===== Form Builder =====
  gripVertical: GripVertical,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  copy: Copy,
  list: List,
  checkSquare: CheckSquare,
  toggleLeft: ToggleLeft,
  table: Table,
  type: Type,
  alignLeft: AlignLeft,
  grid: Grid,
  grid3x3: Grid3x3,
  star: Star,
  slider: Sliders,        // ← Sliders (bukan Slider)
  upload: Upload,
  heading: Heading,
  layout: LayoutIcon,
  page: LayoutIcon,        // ← Pakai LayoutIcon sebagai pengganti Page
  circleDot: CircleDot,
  chevronDown: ChevronDown,
  listChecks: ListChecks,
  phone: Phone,
  calendarIcon: CalendarIcon,
  mailIcon: MailIcon,
  hashIcon: HashIcon,
}

export type IconName = keyof typeof Icons

interface IconProps {
  name: IconName
  className?: string
  size?: number
  onClick?: () => void
}

export function Icon({ name, className = "", size = 20, onClick }: IconProps) {
  const LucideIcon = Icons[name]
  if (!LucideIcon) return null
  return <LucideIcon className={className} size={size} onClick={onClick} />
}